---
- name: Jenkins Provisioning Ubuntu
  hosts: jenkins
  become: yes
  roles:
    - jenkins_install

- name: Sonarqube Provisioning Ubuntu
  hosts: sonar
  become: yes

  roles:
    - sonarqube_install 

- name: Nexus Provisioning Ubuntu
  hosts: nexus
  become: yes

  roles:
    - nexus_install      


